### ISSUE TITLE
Add Gelman's standardize to pystan.preprocessing

### ISSUE THREAD

**Issue by ariddell** [stan-dev/pystan2#334]
#### Summary:

Potential feature. Add Andrew Gelman's standardize function to pystan. Here's the R code: http://www.stat.columbia.edu/~gelman/standardize/standardize.R

I'm hesitant to suggest adding features to pystan since it's potentially more work for the maintainers but I think it's likely the right thing to do in this case.

**Comment by ahartikainen** [comment]
Should we add `.preprocessing` and `.model_selection` tools to pystan? Pystan or external package: pystan-tools?

Anything else that should come with pystan?

**Comment by ariddell** [comment]
My thinking is that we should add these tools anytime we're **certain** that they're likely to be useful to > 25% of PyStan users. Cross validation and preprocessing seem like they fit the bill.

Originally I had thought that these things should be put in separate packages. I've changed my mind recently. If the code is high quality and the tool is obviously useful, it should go in.

Thoughts?

**Comment by ariddell** [comment]
Related discussion #278

**Comment by ahartikainen** [comment]
I guess some preprocessing tools are good to have, but tbh it is so easy to create functions (/ lambda) in python/jupyter notebook so I usually just preprocess data outside pystan (with sklearn, pandas, numpy, scipy tools) and then create and call pystan specifically in the 'last' step. I don't know what is the current situation with R, but if I remember correctly it takes a bit more effort to create and use custom functions, so it makes sense if they have tools built before processing.

But for what it's worth, I think waic and psis-loo (and other model selection tools) should be in pystan because they are hard (or atleast not that easy) to implement on-the-fly and can be really useful (and should be used).

I might be wrong, but it would be great if pystan had a glm / gaussian process toolkit. Maybe those tools should be in external module, outside pystan.

**Comment by ariddell** [comment]
Well, we agree on loo and waic at least. Let's get those in.

p.s. there was one effort to get a glmer like interface for PyStan: https://github.com/dchudz/BayesGLM Seems like the effort is on hiatus.

**Comment by ahartikainen** [comment]
Are we adding them to pystan 2.x or to 3.x?

We could still have some `.preprocessing` functions that are relevant in bayesian computation.

**Comment by ariddell** [comment]
If there's interest in transferring/writing the code for loo and waic (and writing docs and tests), I think we could add it now. The user-facing part of PyStan [is going to change in PyStan 3](https://github.com/stan-dev/stan/wiki/User-Interface-Guidelines-for-Developers) but not that much. The interaction with StanFit objects will, for example, barely change at all.

**Comment by ariddell** [comment]
I'm now wondering if the way golang adds new features is worth copying:
- first a feature is added at golang/x/module
- if/when it's stable, it gets moved to golang/module

Perhaps we could make a ``pystan.hazmat`` or ``pystan.contrib`` submodule which will accept functions which enhance pystan's functionality. It would be understood that there's no guarantee of API stability for these functions. The bar for merging in new functions here would be very low.

**Comment by bob-carpenter** [comment]
There are at least three separate issues:

* is the feature tested and documented?

* is the feature supported?

* will future releases be backward compatible until a major release

I'm asusming you mean that none of these will hold for pystan/x

I'm totally OK with that.  It's not such an issue for the math lib or Stan itself because unless the interfaces also provide the feature, it remains invisible.

**Comment by ariddell** [comment]
These are useful distinctions! I think the new feature need only be (minimally) tested and documented to be included. No guarantees otherwise.

**Comment by ariddell** [comment]
This can definitely go in .experimental
