### ISSUE TITLE
Add support for incremental optimization

### ISSUE THREAD

**Issue by jnboehm** [stan-dev/pystan2#417]
### Summary
I would personally like to be able to incrementally optimize the model, i. e. repeatedly call `model.sampling()` in a loop and be able to look at the intermediate results. 

#### Description
As far as I understand this is possible with the deprecated function `pystan.stan()` (testing this currently), but seeing as it will be removed in the future it should be possible with both `sampling()` and `vb()`.  Maybe it already is and I just did not figure it out, but I did not notice it looking through the online documentation for pystan.

#### PyStan Version:
```python
In [2]: pystan.__version__
Out[2]: '2.17.0.0'
```

#### Python Version:
```sh
python -V
Python 3.6.4
```

**Comment by bob-carpenter** [comment]
Turning the sampler into some kind of iterator would be possible in Python with something like yield if it can be made to block C++ I/O.  The way the underlying C++ is written, Python provides a callback that gets called with each iteration's results.  We decided to move to this architecture so that the interfaces didn't each have to reimplement all the algorithm iteration and boundary conditions.

We wouldn't want to literally call a function like `stan()` in a loop because the `stan()` function specifies warmup and sampling iterations, etc.  Our warmup strategy is rather block oriented, rather than incremental.  The usual problem with runs is that warmup hasn't converged, as diagnosed by multiple chains. This is hard to diagnose until after you run a hundred samples or so.   We don't really have a solution for doing everything incrementally.  There's also the issue of how to coordinate with multiple parallel chains.

What would be very nice is some way to drop in a callback from Python that got notified about each iteration.  That would be workable and it could probably be made to terminate from the outside based on some external condition.

**Comment by jnboehm** [comment]
Thanks for the response and sorry for the late reply.  I could try to work on that if the scope is not too big and I could get some pointers.  Unfortunately, I will not have time the next one and a half weeks but after that should work.

My initial guess would have been that the warmup phase could be decoupled from the sampling process, if the initial parameters could be passed to `sampling()`.  But the callback-oriented approach does make more sense.

**Comment by bob-carpenter** [comment]
The code's all there in repo `stan-dev/stan` in folder `src/stan/services` so you can see how it works. 

Just decoupling into a loop might be relatively simple, though---you might be able to just block on one of the callbacks, for instance.
