### ISSUE TITLE
kernel interrupt not interrupting all workers

### ISSUE THREAD

**Issue by Bonnevie** [stan-dev/pystan2#506]
Working in the Notebook/Lab, it is possible to interrupt the current computation (which can be achieved with ctrl+C in Idle/Ipython IIRC), but when running a pystan HMC sampler it seems that only a few workers/processes get shut off. I often observe continued printing to stdout despite the process ostensibly being stopped according to the IDE. A complete kernel shutdown kills off the last processes as expected.

I recall GPflow had a feature where they'd catch kernel interruptions in order to exit gracefully, I wonder whether the same could be employed here.

**Comment by ahartikainen** [comment]
Yes, I have had the same problem. If I remember right it was due to somehow the current "sitting" lost the handles to subprocesses?

But, yes we can and should see if there are something we can do about the problem.

**Comment by rgerkin** [comment]
In general, I have never successfully interrupted the sampler (or the optimizer) using an interrupt (i.e. "stop") from Notebook/Lab.  It always waits until Stan returns control to Python and then interrupts.  Is there a way for PyStan to expose the process ID of the running Stan process so that Jupyter's interrupts can send a kill signal to that process?
