### ISSUE TITLE
DOC: Optimizing doc is inaccurate 

### ISSUE THREAD

**Issue by jg-you** [stan-dev/pystan2#549]
#### Summary:

Documentation of optimizing does not appear accurate, specifically the `init` parameter

#### Description:

The description of the `init` parameter of `optimizing` is identical to that of `sampling`, with reference to `chains`, which optimizing does not use (as far as I understand).

Behavior does not seem to correlate with choices of init either. For example, initializing at a specified state with init=[state] yields different result even though the algorithm should not be probabilistic (e.g. Newton)

#### Reproducible Steps:

N/A

#### Current Output:

N/A

#### Expected Output:

N/A

#### PyStan Version:

2.18.0.0

#### Python Version:

3.7.1

#### Operating System:

archlinux

**Comment by ahartikainen** [comment]
Thanks for the bug report.

Yes, there shouldn't be anything on chains.

I'm not totally sure, but the problem with `init` is that the random state it set at the model compilation, so even with the identical inits there can be difference between runs. (Cc @riddell-stan )

This `init` vs seed problem should be fixed with PyStan3. (I'm not sure optimization is yet implemented)

**Comment by ahartikainen** [comment]
Just one quick question, does this work as expected with CmdStan?

**Comment by jg-you** [comment]
I have not tried to call CmdStan directly.

**Comment by bob-carpenter** [comment]
As far as I know, CmdStan does the right thing in that it'll return the same thing for the same inputs and same seed.

If not all the data variables are specified in the init and the random number seed isn't specified, then the missing variables are randomly initialized in a way that won't be reproducible.
