### ISSUE TITLE
FYI: Missing header file issue on Mac OSX 10.14

### ISSUE THREAD

**Issue by MooersLab** [stan-dev/pystan2#639]
#### Summary:
studio.h header file not found by PyStan 2.19  on Mac OSX 10.14.

#### Description:
I installed PyStan 2.19 with pip on Mac OSX 10.14 for python3.7m  but it would not run pystan.stanc when I tried to compile a model.
PyStan could not find studio.h.
PyStan was looking for C++ headers in /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk.
This file was missing, perhaps due to a system update that I made early last week.
I had to reinstall the command line tools.

There was a MacOSX10.15.sdk and a MacOSX.sdk file in the above folder but not the expected MacOSX10.14.sdk file.
I linked MacOSX10.14.sdk to MacOSX.sdk.

Now, PyStan is working :smile:.

```bash
cd /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs
sudo ln -s MacOSX.sdk  MacOSX10.14.sdk
```

**Comment by ahartikainen** [comment]
Great it works now. Yes, we are missing some good docs on how to solve this issue on macOS.

The problem comes from the fact that macOS `clang` started using `libc++` where they previously used `libstdc++`. In discourse, there are some instructions about how to handle this, but currently, I don't know any universal (easy) solution.
